import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  Raleway,
  Montserrat,
} from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { BackgroundRippleEffect } from "@/components/ui/background-ripple-effect";
import { AppSidebar } from "@/components/app-sidebar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${inter.variable} ${raleway.variable} ${montserrat.variable} antialiased font-sans`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="flex flex-col px-[16px] py-[10px] gap-[20px] max-h-screen w-full">
            <div className="relative flex flex-row -mt-[10px] py-[10px] items-center gap-[14px]">
              <BackgroundRippleEffect rows={4} cellSize={46} />
              <SidebarTrigger className="relative z-20" />
              <p className="relative z-20 text-[16px] font-semibold tracking-tight leading-none text-zinc-200">
                ToothWise
              </p>
            </div>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
